### ISSUE TITLE
“Next page” button missing

### ISSUE THREAD

**Issue by pabloest** [returntocorp/docs#46]
This [feedback comes](https://github.com/flip1995/r2c-clippy/blob/master/r2c_feedback.md) from user @flip1995: “Button for next page instead of link at end of page”

There is already a TOC shown on the left side of the page, but it’s possible the user did not notice the TOC nav, or did not see it when scrolled to the bottom of the page. Possible solutions:

1. add “Prev” and “Next” buttons as suggested by the user
2. in the TOC, highlight the page currently in view so it’s easier to see what’s next in the sequence
3. make the TOC sticky so it stays visible as the user scrolls
4. implement both 2 and 3 from above

**Comment by flip1995** [comment]
I think making the TOC sticky is the best idea regarding the TOC.

But my issue with this was a bit different: When you read through a continuous introduction doc like this it's more like reading a book, where you flip through the pages (prev/next button), rather than going to a new book (link to next page) every time you finish a chapter. (At least, that's my view from the HCI side of things, but opinions may differ obviously)

I think the [Rust book](https://doc.rust-lang.org/book/ch01-00-getting-started.html)s are doing a great job here, where you can even go through the book with the arrow keys, what even more feels like reading a book.

**Comment by pabloest** [comment]
@flip1995 Thanks so much for the additional context and the tip about the Rust books. We’ll look at those to help inform the way forward here.

**Comment by pabloest** [comment]
Hi @flip1995, just to let you know we updated the docs navigation today at [https://docs.r2c.dev ](https://docs.r2c.dev )based on your feedback. Thanks again for sharing it with us!
